splice!(LOAD_PATH, 1:0, ["/Users/kishorehari/Desktop/Boolean.jl"])
using Boolean
cd("src")
include("dependencies.jl")
include("utils.jl")
include("async_update.jl")
include("multiLevel_shubham_copy.jl")
include("CSB.jl")
include("async_non_matrix.jl")
include("customFunctions.jl")
include("oddLevel.jl")
include("logicalRules.jl")
include("bmodel.jl")
cd("../data")