splice!(LOAD_PATH, 1:0, ["/Users/kishorehari/Desktop/Boolean.jl"])
using Boolean
# cd("src")
include("src/dependencies.jl")
include("src/utils.jl")
include("src/async_update.jl")
include("src/multiLevel_shubham_copy.jl")
include("src/CSB.jl")
include("src/async_non_matrix.jl")
include("src/customFunctions.jl")
include("src/oddLevel.jl")
include("src/logicalRules.jl")
include("src/logicalSim.jl")
include("src/bmodel.jl")
cd("data")